# codecentric
## https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#configuration
image:
  repository: opentdf/keycloak
  tag: 16.1.1-r2-arm64

extraEnv: |
  - name: KEYCLOAK_LOGLEVEL
    value: INFO
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://localhost:65432/keycloak/auth/"
  - name: KEYCLOAK_USER
    value: keycloakadmin
  - name: KEYCLOAK_PASSWORD
    value: mykeycloakpassword

ingress:
  enabled: true
  servicePort: https
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  rules:
    -
      host: localhost
      paths:
        - path: /keycloak(/|$)(.*)
          pathType: ImplementationSpecific

  tls:
  - hosts:
    - localhost
