image:
  repository: ghcr.io/opentdf/keycloak
  # Keycloak is a non-OpenTDF chart, but with an OpenTDF image
  tag: 15.1.1-r13-dcr
postgresql:
  enabled: false
  postgresqlUsername: postgres
  postgresqlPassword: mydbapassword
  postgresqlDatabase: keycloak_database
externalDatabase:
  host: opentdf-postgresql
  user: postgres
  password: mydbapassword
  database: keycloak_database
extraEnv: |
  - name: CLAIMS_URL
    value: http://entitlement-pdp:3355/entitlements
# - name: DB_VENDOR
#   value: postgres
# - name: DB_ADDR
#   value: postgresql
# - name: DB_DATABASE
#   value: keycloak_database
# - name: DB_PORT
#   value: "5432"
# - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
#   value: "true"
# - name: KEYCLOAK_FRONTEND_URL
#   value: "http://localhost:65432/auth"
# - name: KEYCLOAK_LOG_LEVEL
#   value: DEBUG
extraEnvFrom: |
  - secretRef:
      name: 'keycloak-secrets'
ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: localhost
      paths:
        - path: /auth(/|$)(.*)
          pathType: Prefix
    - host: host.docker.internal
      paths:
        - path: /auth(/|$)(.*)
          pathType: Prefix
  tls: null

