name: Quickstart workflow
on: [push]
jobs:
  quickstart-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            helm
            tilt
          # This should be in sync with the minikube-deployed kube version below
          kubectl: "1.23.3"
          helm: "3.8.0"
          helmv3: "3.8.0"
          tilt: "0.25.2"
      - run: |
          kustomize version
          tilt version
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 1.25.2
          # This should be in sync with the setup-tools version above
          kubernetes-version: 1.23.3
      - name: Get cluster versions
        run: |-
          kubectl version
          kubectl get pods -A
      - name: Run Tiltfile
        run: |-
          cd quickstart
          tilt ci
      - run: echo "🍏 Job status is ${{ job.status }}."
